# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    desc: "Compila tanto el servidor Go como el cliente Vala"
    cmds:
      - task: build-server
      - task: build-client

  build-servidor:
    desc: "Compila el servidor Go"
    cmds:
      - mkdir -p bin
      - go build -o bin/Servidor ./src/main/go

  build-cliente:
    desc: "Compila el cliente Vala con dependencias Gio y Json-Glib"
    cmds:
      - mkdir -p bin
      - valac --pkg gio-2.0 --pkg json-glib-1.0 -X -w ./src/main/vala/*.vala -o bin/Cliente
     
  run-servidor:
    desc: "Ejecuta el servidor"
    cmds:
      - ./bin/Servidor {{.CLI_ARGS | default "5050"}}

  run-cliente:
    desc: "Ejecuta el cliente"
    cmds:
      - ./bin/Cliente {{.CLI_ARGS}}   
    
  clean:
    desc: "Elimina los programas compilados"
    cmds:
      - rm -rf bin/
    
